version: "3"

services:
  portfolio:
    build:
      context: ../server/
      dockerfile: ../development/Dockerfile
    env_file:
      - .env
    volumes:
      - ../server:/portfolio/server
      - ../images:/portfolio/images
    ports:
      - "3000:3000"
    entrypoint: dockerize -timeout 60s -wait tcp://db:3306
    command: fresh -c fresh.conf
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portfolio
    ports:
      - "3306:3306"
    expose:
      - "3306"
