openapi: 3.0.1

info:
  description: "prtfolioについてのAPI"
  version: v1
  title: "portfolio API"
  termsOfService: "http://swagger.io/terms/"

servers:
  - url: /api

paths:
  /category:
    get:
      tags:
        - for client
      description: クライアント用のメインカテゴリー一覧を取得
      responses:
        200:
          description: メインカテゴリーの一覧
          content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/MainCategory"

components:
  schemas:
    MainCategory:
      description: メインカテゴリー
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        created_at:
          type: string
          format: date-time
          example: "2019-04-01T12:00:00+09:00"
        updated_at:
          type: string
          format: date-time
          example: "2019-04-01T12:00:00+09:00"
        sub_categories:
          type: array
          items:
            $ref: "#/components/schemas/SubCategory"
    
    SubCategory:
      description: メインカテゴリー
      type: object
      properties:
        id:
          type: string
        main_category_id:
          type: string
          description: 親のメインカテゴリーのID
        name:
          type: string
        description:
          type: string
        created_at:
          type: string
          format: date-time
          example: "2019-04-01T12:00:00+09:00"
        updated_at:
          type: string
          format: date-time
          example: "2019-04-01T12:00:00+09:00"